### ISSUE TITLE
How to run multiple services using EFFK

### ISSUE THREAD

**Issue by rbk111088** [newrelic/fluentbit-examples#4]
Hello,

I need some help how to centralize logging for multiple services using Elastic, Fluent-Bit, FluentD and Kibana in Docker

In my case,

A service, i kept all in place of EFFK stacks, its coming Docker when i run docker-compose up

and i try to run B service but i fail with below Error

docker-compose up
ERROR: Service 'fluent-bit' has a link to service 'fluentd' which is undefined.

i am attaching Docker-compose.yml of both services.
[docker-compose_B Service.txt](https://github.com/newrelic/fluentbit-examples/files/6602981/docker-compose_B.Service.txt)
[docker-compose_A Service.txt](https://github.com/newrelic/fluentbit-examples/files/6602982/docker-compose_A.Service.txt)

Kindly help me asap, its blocking my work.

**Comment by danybmx** [comment]
Hi @rbk111088,

Thanks for reaching out.

These examples are meant to be used with NewRelic fluent-bit output plugin. If you are experiencing a problem trying to send logs to New Relic please check if there is an open topic in our New Relic Explorers Hub: [Log forwarding](https://discuss.newrelic.com/tag/log-forwarding). In case your not using NR, maybe you could ask for help on the official [fluent-bit](https://github.com/fluent/fluent-bit) / [fluentd](https://github.com/fluent/fluentd) repositories. I will proceed to close this issue. 

Regards!
